[package]
name = "orbita3d_kinematics"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.20"
levenberg-marquardt = "0.14.0"
nalgebra = { version = "0.33.2", default-features = false, features = ["libm"]}
ndarray = { version = "0.16.1", default-features = false }
ndarray_einsum_beta = { git = "https://github.com/bangconghuynh/einsum.git", default-features = false, optional = true}
nshare = { version = "0.10.0", default-features = false, features = ["nalgebra", "ndarray"]}
serde = { version = "1.0.183", default-features = false, features = ["derive"] }
num-traits = { version = "0.2.19", default-features = false, features = ["libm"] }

[features]
default = ["forward_kinematics"]
forward_kinematics = ["std", "dep:ndarray_einsum_beta"]
std = []

[dev-dependencies]
rand = "0.8.5"
