io: !DynamixelPoulpe
  serial_port: /dev/ttyACM0
  id: 42
  use_cache: false
disks:
  zeros: !ZeroStartup
  reduction: 4.2666667
kinematics_model:
  alpha: 0.9424777960769379 # 54 degrees
  gamma_min: 0.6981317007977318 # 40 degrees
  offset: 0.0
  beta: 1.5707963267948966 # 90 degrees
  gamma_max: 3.141592653589793 # 180 degrees
  passiv_arms_direct: true
