<?xml version="1.0" ?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:include filename="$(find pollen_generic_description)/urdf/inertial_primitives.urdf.xacro"/>
  <xacro:include filename="$(find pollen_generic_description)/urdf/materials.urdf.xacro"/>
  <xacro:include filename="$(find orbita3d_description)/ros2_control/orbita3d.ros2_control.xacro"/>

  <xacro:macro name="orbita3d" params="name parent length radius mass xyz rpy damping friction config_file">

    <!--
      Orbita3d

    link                         (joint)

    ${parent}                    (${name}_base_joint) fixed
      ${name}_base_link          (${name}_roll) revolute
        ${name}_dummy_link1      (${name}_pitch) revolute
          ${name}_dummy_link2    (${name}_yaw) revolute
            ${name}_link         (${name}_ball_joint) fixed
              ${name}_ball_link
    -->


    <link name="${name}_dummy_link1">
      <xacro:inertial_cuboid mass="${mass*0.01}" xyz="0 0 0"  rpy="0 0 0" x_length="${radius*2}" y_length="${radius*2}" z_length="${length}">
      </xacro:inertial_cuboid>
    </link>

    <link name="${name}_dummy_link2">
      <xacro:inertial_cuboid mass="${mass*0.01}" xyz="0 0 0"  rpy="0 0 0" x_length="${radius*2}" y_length="${radius*2}" z_length="${length}">
      </xacro:inertial_cuboid>
    </link>

    <link name="${name}_link">
      <!-- <visual> -->
      <!-- 	<origin xyz="0 0 0" rpy="0 0 0"/> -->
      <!-- 	<geometry> -->
      <!--     <cylinder length="${length}" radius="${radius}"/> -->
      <!-- 	</geometry> -->
      <!-- 	<xacro:orbita3d_grey/> -->
      <!-- </visual> -->

      <!-- <collision> -->
      <!-- 	<origin xyz="0 0 ${length/2}" rpy="0 0 0"/> -->
      <!-- 	<geometry> -->
      <!--     <cylinder length="${length}" radius="${radius}"/> -->
      <!-- 	</geometry> -->
      <!-- </collision> -->

      <xacro:inertial_cuboid mass="${mass*0.98}" xyz="0 0 ${-length/2}"  rpy="0 0 0" x_length="${radius*2}" y_length="${radius*2}" z_length="${length}">
      </xacro:inertial_cuboid>
    </link>

    <link name="${name}_ball_link">
      <!-- <visual> -->
      <!-- 	<origin xyz="0 0 0" rpy="0 0 0"/> -->
      <!-- 	<geometry> -->
      <!--     <sphere radius="${radius*1.2}"/> -->
      <!-- 	</geometry> -->
      <!-- 	<xacro:orbita3d_grey/> -->

      <!-- </visual> -->
      <!-- <collision> -->
      <!-- 	<origin xyz="0 0 0" rpy="0 0 0"/> -->
      <!-- 	<geometry> -->
      <!--     <sphere radius="${radius*1.2}"/> -->
      <!-- 	</geometry> -->
      <!-- </collision> -->
      <!-- <xacro:inertial_sphere mass="${mass*0.5}" diameter="${2*radius*1.2}"/> -->
      <inertial>
        <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
        <mass value="0.001"/>
        <inertia ixx="1.0e-6" ixy="1.0e-8" ixz="1.0e-8" iyy="1.0e-6" iyz="1.0e-8" izz="1.0e-6"/>
      </inertial>
    </link>

    <joint name="${name}_ball_joint" type="fixed">

      <origin xyz="0 0 0" rpy="0 0 0"/>
      <parent link="${name}_link"/>
      <child link="${name}_ball_link"/>
    </joint>

    <link name="${name}_base_link">
      <!-- <visual> -->
      <!-- 	<origin xyz="0 0 0.0672" rpy="0 0 0"/> -->
      <!-- 	<geometry> -->
      <!--     <cylinder radius="0.0278" length="0.0336"/> -->
      <!-- 	</geometry> -->
      <!-- 	<xacro:orbita3d_grey/> -->
      <!-- </visual> -->
      <inertial>
        <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
        <mass value="0.001"/>
        <inertia ixx="1.0e-6" ixy="1.0e-8" ixz="1.0e-8" iyy="1.0e-6" iyz="1.0e-8" izz="1.0e-6"/>
      </inertial>
    </link>

    <joint name="${name}_base_joint" type="fixed">

      <!-- <origin xyz="0 0 0" rpy="0 0 0"/> -->
    <xacro:if value="${name == 'r_wrist'}">
      <origin xyz="${xyz}" rpy="3.141592 0 1.5707963267948966"/>
    </xacro:if>
    <xacro:if value="${name == 'l_wrist'}">
      <origin xyz="${xyz}" rpy="3.141592 0 1.5707963267948966"/>
    </xacro:if>
    <xacro:if value="${name == 'neck'}">
      <origin xyz="${xyz}" rpy="${rpy}"/>
    </xacro:if>

      <parent link="${parent}"/>
      <child link="${name}_base_link"/>
    </joint>



    <link name="${name}_out_link">
      <inertial>
        <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
        <mass value="0.001"/>
        <inertia ixx="1.0e-6" ixy="1.0e-8" ixz="1.0e-8" iyy="1.0e-6" iyz="1.0e-8" izz="1.0e-6"/>
      </inertial>
    </link>

    <joint name="${name}_out_joint" type="fixed">

      <!-- <origin xyz="0 0 0" rpy="0 0 0"/> -->
    <xacro:if value="${name == 'r_wrist'}">
      <origin xyz="0 0 0" rpy="3.141592 0 0"/>
    </xacro:if>
    <xacro:if value="${name == 'l_wrist'}">
      <origin xyz="0 0 0" rpy="3.141592 0 0"/>
    </xacro:if>
    <xacro:if value="${name == 'neck'}">
      <!-- <origin xyz="0 0 0" rpy="3.141592 0 0"/> -->
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </xacro:if>

      <parent link="${name}_ball_link"/>
      <child link="${name}_out_link"/>
    </joint>



    <joint name="${name}_roll" type="revolute">
      <!-- <origin xyz="${xyz}" rpy="${rpy}"/> -->
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <!-- <parent link="${parent}"/> -->
      <parent link="${name}_base_link"/>

      <child link="${name}_dummy_link1"/>
      <axis xyz="1 0 0"/>
      <limit lower="-0.35" upper="0.35" effort="1000.0" velocity="100.0"/>
      <dynamics damping="${damping}" friction="${friction}"/>
    </joint>

    <joint name="${name}_pitch" type="revolute">
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <parent link="${name}_dummy_link1"/>
      <child link="${name}_dummy_link2"/>
      <axis xyz="0 1 0"/>
      <limit lower="-0.35" upper="0.35" effort="1000.0" velocity="100.0"/>
      <dynamics damping="${damping}" friction="${friction}"/>
    </joint>

    <joint name="${name}_yaw" type="revolute">
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <parent link="${name}_dummy_link2"/>
      <child link="${name}_link"/>
      <axis xyz="0 0 1"/>
      <limit lower="-1.57" upper="1.57" effort="1000.0" velocity="100.0"/>
      <dynamics damping="${damping}" friction="${friction}"/>
    </joint>

    <xacro:orbita3d_control
      name="${name}"
      config_file="${config_file}"
    />

  </xacro:macro>
</robot>
