name: Python checks

on: [push]

jobs:
  python-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Deps
        run: |
          sudo apt-get update
          sudo apt-get install -y libudev-dev

      - name: Install protc
        run: sudo apt install -y protobuf-compiler libprotobuf-dev
          
      - name: Install Mercurial
        run: sudo apt-get install -y mercurial
          
      - name: Set up IgH repo
        run: |
          hg clone http://hg.code.sf.net/p/etherlabmaster/code ethercat-hg
          cd ethercat-hg
          hg update stable-1.5
          ./bootstrap
          ./configure --disable-8139too
          export ETHERCAT_PATH=$(pwd)/ethercat-hg
          
      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Setup Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true


      - name: Maturin
        run: |
          pip install --upgrade pip
          python -m venv env
          source env/bin/activate
          pip install maturin

          cd orbita3d_c_api
     
          maturin develop
          python -c "import orbita3d"

          pip install coverage pytest flake8
          coverage run -m pytest

          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --exclude python/orbita3d/_orbita3d
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=128 --statistics --exclude python/orbita3d/_orbita3d

        
