name: Python checks

on: [push]

jobs:
  python-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Deps
        run: |
          sudo apt-get update
          sudo apt-get install -y libudev-dev

      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Maturin
        run: |
          pip install --upgrade pip
          python -m venv env
          source env/bin/activate
          pip install maturin

          cd orbita3d_c_api

          maturin develop
          python -c "import orbita3d"

          pip install coverage pytest flake8
          coverage run -m pytest

          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --exclude python/orbita3d/_orbita3d
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=128 --statistics --exclude python/orbita3d/_orbita3d

        